# Generated by Django 6.0.2 on 2026-08-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmeks', '0002_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['display_order', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='link',
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.URLField(blank=True, verbose_name='GitHub URL'),
        ),
        migrations.AddField(
            model_name='project',
            name='live_demo',
            field=models.URLField(blank=True, verbose_name='Live Demo URL'),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.CharField(default=1, help_text='Example: Django, PostgreSQL, Bootstrap, Docker', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Full description.'),
        ),
    ]
